server {
    listen 80;
    server_name openllm.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name openllm.cloud;

    ssl_certificate /etc/ssl/openllm.cloud_bundle.crt;
    ssl_certificate_key /etc/ssl/openllm.cloud.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /api/ {
        proxy_pass http://llmops-api:5001/;
        include proxy.conf;
    }

    location / {
        proxy_pass http://llmops-ui:3000;
        include proxy.conf;
    }
}
